export declare enum BehaviorTypeCode {
    UNDEFINED = 0,
    INNOVI_CROSSING = 1,
    INNOVI_MOVING = 2,
    INNOVI_STOPPED = 3,
    INNOVI_OCCUPANCY = 4,
    INNOVI_GROUPING = 5,
    INNOVI_MASK_IGNORE = 100,
    INNOVI_MASK_SHUTDOWN = 101,
    INNOVI_ANOMALY = 200,
    HARD_HAT_EXISTS = 1001,
    HARD_HAT_NOT_EXISTS = 1002,
    TRASH_EXISTS = 1101,
    TRASH_NOT_EXISTS = 1102,
    MCC_EXISTS = 1201,
    MCC_NOT_EXISTS = 1202
}
