export declare enum EntityTypeCode {
    UNDEFINED = 0,
    ACCOUNT = 1,
    FOLDER = 2,
    APPLIANCE = 3,
    AGENT = 4,
    SENSOR = 5,
    RULE = 6,
    EVENT = 7,
    HEALTH_EVENT = 8,
    SENSOR_STATUS = 9,
    AGENT_STATUE = 10,
    APPLIANCE_STATUS = 11,
    CALENDAR = 12,
    SCHEDULE = 13,
    DIGITAL_IO = 14,
    FEATURE = 18,
    FEATURES_GROUP = 19,
    USER = 20
}
