export declare enum RuleTypeCode {
    UNDEFINED = 0,
    INNOVI_RULE_CROSSING = 1,
    INNOVI_RULE_MOVING = 2,
    INNOVI_RULE_STOPPED = 4,
    INNOVI_RULE_OCCUPANCY = 8,
    INNOVI_RULE_GROPPING = 16,
    INNOVI_ANOMALY = 2048,
    CUSTOM_HARD_HAT = 4096,
    CUSTOM_TRASH = 8192,
    CUSTOM_MCC = 16384
}
