export declare enum SensorStatusMask {
    SENSOR_OK = 0,
    SENSOR_ERROR = 1,
    NO_COMM_ERROR = 8,
    SOURCE_ERROR = 16,
    UNSUPPORTED_FORMAT = 32,
    UNSUPPORTED_RESOLUTION = 64,
    FRAMERATE_LOW = 256,
    FRAMERATE_HIGH = 512,
    FRAMERATE_CRITICAL = 1024,
    IMAGE_BLOCKED = 4096,
    IMAGE_SATURATED = 8192,
    IMAGE_DARK = 16384
}
